### PR TITLE
patched plugin tyring to set color for noncolor tool

### LINKED ISSUE #32: Plugin error when using non-color tools (eraser, select, etc.)
**Description**

When running Xournal++ with the `vi-xournalpp` plugin enabled, whenever I try to change color with the plugin, the following warning is raised if the current tool does not support colors (e.g., eraser, select, etc.):

```bash
(com.github.xournalpp.xournalpp:223922): xopp-WARNING **: 04:12:57.128: Error in Plugin: "vi-xournalpp", error: "...ssef-adly/.config/xournalpp/plugins/vi-xournalpp/api.lua:112: tool "eraser" has no color capability"
```

**Expected Behavior**

The plugin should not attempt to apply colors to tools that do not support them.

**Actual Behavior**
The plugin tries to access the color capability of the current tool, which fails for non-color tools.

**Proposed Fix**
Before applying colors, check whether the current tool is one of:

- pen
- highlighter
- laser
- etc...

If it is not one of these, skip the color assignment.

I can implement this myself

### PR DESCRIPTION
**Pull request by youssefadly237**
used `getToolInfo` to check the active tool, and its properties to determine if it has color capability or not  (dynamic)

fixes #32

### CODE REVIEW

File: api.lua [hunk 1]
```diff
@@ -104,10 +108,26 @@ end
...
+	local toolType = activeToolInfo["type"] or "unknown"
+	-- get the info for that specific tool
+	local toolInfo = getToolInfo(toolType)
+	if not toolInfo then return end
+	-- Check if this tool really has a color property
+	if toolInfo["color"] ~= nil then
+		local ok = pcall(function()
+			app.changeToolColor({ ["color"] = color, ["selection"] = true })
+		end)
+		if ok and toolType ~= "text" then
```
Comment (lryffel) [inline api.lua:123]: Why does it need to be `ok` in order to change the color of the text tool? If I change the color on the eraser I want the next LaTeX insert to be the new color.

File: api.lua [hunk 2]
```diff
@@ -104,10 +108,26 @@ end
...
+	if not activeToolInfo then return end
+	local toolType = activeToolInfo["type"] or "unknown"
+	-- get the info for that specific tool
+	local toolInfo = getToolInfo(toolType)
+	if not toolInfo then return end
+	-- Check if this tool really has a color property
+	if toolInfo["color"] ~= nil then
+		local ok = pcall(function()
+			app.changeToolColor({ ["color"] = color, ["selection"] = true })
+		end)
```
Comment (lryffel) [inline api.lua:122]: Why not just  `pcall(function() app.changeToolColor({ color = color, selection = true }) end)`? This will just do nothing if the color property doesn't exist, and otherwise do nothing, I think. (I admit, I asked ChatGPT to simplify)

Comment (youssefadly237) [reply api.lua:122]: zen of python, never pass silently ? (I know this is Lua)
this approach works, but it will just print the color in the terminal without telling me that this tool does not support changing colors
